version: '3.4'

services:
  hardhatsample:
    image: hardhatsample
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
